# Taken from https://github.com/kikito/middleclass/blob/master/.travis.yml
os: linux
language: python
sudo: false

env:
  - LUA="lua=5.2 --compat=none"
  - LUA="lua=5.3 --compat=none"
  - LUA="luajit=2.0 --compat=5.2"
  - LUA="luajit=2.1 --compat=5.2"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks make rockspec/*-master-1.rockspec

script:
  - luacheck --std max+busted src/ test/
  - busted --verbose --coverage --pattern=".test.lua" --recursive src/

after_success:
  - luacov-coveralls --exclude "test" --exclude "lua_install"

notifications:
  recipients:
    - alban@linard.fr
  email:
    on_success: change
    on_failure: always
